version: '2'
services:
  appiron-app:
    image: appiron
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://appiron-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=APPIRON
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://appiron-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://appiron-elasticsearch:9200
    ports:
      - 8080:8080
  appiron-mongodb:
    extends:
      file: mongodb.yml
      service: appiron-mongodb
  appiron-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: appiron-elasticsearch
